version: '3'

services:
  postgres:
    image: postgres:12
    container_name: egts_pg_test
    environment:
      POSTGRES_USER: egts
      POSTGRES_PASSWORD: egts
      POSTGRES_DB: receiver
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: egts_redis_test
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    container_name: egts_mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: egts
      MYSQL_USER: egts
      MYSQL_PASSWORD: egts
      MYSQL_DATABASE: receiver
    ports:
      - "3306:3306"

  # egts:
  #   image: egts:latest
  #   container_name: egts_receiver
  #   ports:
  #     - "6000:6000"

  #   volumes:
  #     - ./configs:/etc/egts-receviver/
