host = "127.0.0.1"
port = "6000"
con_live_sec = 10
log_level = "DEBUG"

# [store]
# plugin = "rabbitmq.so"
# host = "localhost"
# port = "5672"
# user = "guest"
# password = "guest"
# exchange = "receiver"