name: Deploy to dwh3

on:
  workflow_dispatch

jobs:
  build_deploy_to_dwh3:
    name: Build and deploy
    runs-on: [self-hosted, db-dwh3]
    timeout-minutes: 30
    env:
      CONTAINER_NAME: "egts-receiver-time"
      IMAGE_NAME: "egts-timestamp"
      CONTAINER_PORT: "6000"
    steps:
      - name: Check for actual
        uses: actions/checkout@v4
        with:
          path: .
      
      - name: Copy config file
        run: |
          cp /home/admin/Downloads/configs/receiver.yaml ./configs/receiver.yaml
      
      - name: Build
        run: >
          docker build
          -t ${{ env.IMAGE_NAME }}:latest
          --no-cache
          .

      - name: Stop previous
        run: >
          CONTAINER_EXISTS=$(docker ps -a --format '{{.Names}}' --filter "name=${{ env.CONTAINER_NAME }}" -a | wc -w);
          if  [[ $CONTAINER_EXISTS != 0 ]] ;
          then docker container stop ${{ env.CONTAINER_NAME }};
          docker container rm ${{ env.CONTAINER_NAME }};
          else echo "Container ${{ env.CONTAINER_NAME }} does not exist";
          fi

      - name: Run container
        run: >
          docker run
          --restart unless-stopped
          --name ${{ env.CONTAINER_NAME }}
          -v /etc/hosts:/etc/hosts
          -v ./configs/receiver.yaml:/etc/egts-receviver/config.yaml
          -p ${{ env.CONTAINER_PORT }}:6000
          -d
          ${{ env.IMAGE_NAME }}

      - name: Perform cleanup
        run: docker system prune -f
